# Generated by Django 2.2.16 on 2022-07-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220714_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.CharField(blank=True, max_length=254, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Rating'),
        ),
    ]
