# Generated by Django 2.2.16 on 2022-07-19 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20220719_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(
                blank=True,
                default='John',
                max_length=30,
                verbose_name='first name',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(
                blank=True,
                default='Doe',
                max_length=150,
                verbose_name='last name',
            ),
            preserve_default=False,
        ),
    ]
